### ISSUE TITLE
Possible concurrency issue when starting upload

### ISSUE THREAD

**Issue by tiwiz** [bertrandmartel/speed-test-lib#11]
Hello,

I noticed something a bit strange: when starting the upload, often I get very wrong values  (such as 200 Mbps in lines where the average is 1). It usually takes 3 to 4 "onUpdateProgress" call to stabilise it.

Here's an extract of the measurement I get:
`D/SpeedTestPresenter: Current speed of 0,00 Mbps.
D/SpeedTestPresenter: Current speed of 50,00 Mbps.
D/SpeedTestPresenter: Current speed of 62,50 Mbps.
D/SpeedTestPresenter: Current speed of 76,92 Mbps.
D/SpeedTestPresenter: Current speed of 2,53 Mbps.
D/SpeedTestPresenter: Current speed of 1,39 Mbps.
D/SpeedTestPresenter: Current speed of 1,07 Mbps.
D/SpeedTestPresenter: Current speed of 0,92 Mbps.
D/SpeedTestPresenter: Current speed of 0,83 Mbps.
D/SpeedTestPresenter: Current speed of 0,77 Mbps.
D/SpeedTestPresenter: Current speed of 0,72 Mbps.
D/SpeedTestPresenter: Current speed of 0,67 Mbps.
D/SpeedTestPresenter: Current speed of 0,65 Mbps.
D/SpeedTestPresenter: Current speed of 0,63 Mbps.
D/SpeedTestPresenter: Upload: MAX 76,92 Mbps - AVG 14,26 Mbps`

**Comment by akinaru** [comment]
Hi, thank you for reporting this. From the title `concurrency issue`, do you have this issue when issuing multiple upload request on the same object ? Is 14,26 Mbps in your example the result from `onUploadPacketsReceived` ?

**Comment by tiwiz** [comment]
No, the average is a calculated on the list of values I get. At the moment I only do one upload... From the `onUploadPacketsReceived` I can get the average as well? That would be very cool!

**Comment by akinaru** [comment]
Yes `onUploadPacketsReceived` gives you the total average on the speed test duration. In `onProgress` callback that only gives you current average at that time of the speed test

```
@Override
public void onUploadPacketsReceived(int packetSize, float transferRateBitPerSeconds, 
                                    float transferRateOctetPerSeconds) {
    System.out.println("this is the average in bps     : " + 
               transferRateBitPerSeconds + " bps");
    System.out.println("this is the average in octet   : " +
               transferRateOctetPerSeconds + "Bps");
}
```

**Comment by akinaru** [comment]
I cant reproduce your weird large transfer rate values at the beginning of upload test (I tried nested upload infinite loop), can you share how do you reproduce it ?

**Comment by tiwiz** [comment]
Sure, I use these routines:

```


    override fun onDownloadCompleted() {
        Timber.d("Download: MAX ${downloadCallback.max().format(2)} Mbps - AVG ${downloadCallback.avg().format(2)} Mbps")
        view.showUploadIcon()
        resetUi()
        startUpload(1000000)
    }

    private fun resetUi() {
        view.updateProgressTo(0)
        view.updateGaugeTo(0)
        view.updateSpeedWith("")
    }

    private fun startUpload(octet: Int = 10000000) {
        Observable.fromCallable { socket.startUpload(host, port, uploadFile, octet) }
                .delay(3, TimeUnit.SECONDS)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe()
    }
```

**Comment by akinaru** [comment]
Do you still have the issue if you remove UI operation or other blocking from all the SpeedTestListener callback ? In you `onProgress` do you perform UI or blocking stuff ? As the content of `onProgress` is running in writing thread for upload and reading thread for download, all blocking operation should be run in a different thread

**Comment by tiwiz** [comment]
Actually, the callbacks are the only thing happening on the main thread, all the rest is moved from the main thread

**Comment by akinaru** [comment]
Just to be sure it is not network specific 
```
git clone git://github.com/akinaru/speed-test-lib.git
cd speed-test-lib
./gradlew uploadFile
```
Do you confirm that you have the same behavior with that test ? Thank you very much for your time

**Comment by tiwiz** [comment]
Yup,

it looks like I'm on a 500Mbps line (at work I'm on a 100Mbps one)

**Comment by tiwiz** [comment]
Short update: I managed to fix the issue on Android and I opened a PR :-)

**Comment by bertrandmartel** [comment]
Hello, thank you for the PR, I've implemented a method to set the setup time for download/upload 
* download
`speedTestSocket.setDownloadSetupTime(5000);`
* upload
`speedTestSocket.setUploadSetupTime(5000);`

The setup time is the time from which the speed test rate is calculated as you've defined in your PR

This would take into account your issue and TCP congestion problem but would require to manually set this setup time.
