### ISSUE TITLE
SpeedTestReport : getTransferRateBit() 

### ISSUE THREAD

**Issue by NickGuaGua** [bertrandmartel/speed-test-lib#19]
public void onDownloadProgress(float percent, SpeedTestReport report) {
        report.getTransferRateBit()
}
The result will be cumulatively.
I think the calculation seems to be wrong, and here is my calculation :

                float getTemporaryPacketSize = report.getTemporaryPacketSize();
                float intervalDLSize = getTemporaryPacketSize-tempSize;
                tempSize = getTemporaryPacketSize;

                if(tempDLTime ==0)
                    tempDLTime = report.getStartTime();

                long getReportTime = report.getReportTime();
                long intervalDLTime = getReportTime-tempDLTime ;
                tempDLTime = getReportTime;

                float mKBps = (intervalDLSize/intervalDLTime)*1000/8/1000 ;

**Comment by bertrandmartel** [comment]
> The result will be cumulatively

Yes, it will give you the speed test rate on the whole period (cumulating all the speed rate obtained from the chunks uploaded/downloaded during that time)
