### ISSUE TITLE
Java compativility issue

### ISSUE THREAD

**Issue by xgear-public** [bertrandmartel/speed-test-lib#20]
Trying to build android project with speed-test-lib but during build got following error:

Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.

**Comment by xgear-public** [comment]
Looks like issue appeared in 1.24. Project builded with 1.23 successfully.

**Comment by bertrandmartel** [comment]
Hello, thank you I've released 1.25 that fix this issue. It has already been released in JCenter, for MavenCentral it will sync soon.

**Comment by xgear-public** [comment]
Thank you for your lib and blazing fast support!

**Comment by xgear-public** [comment]
@bertrandmartel I want to integrate your library into android project. Approximately users will generate 10k - 50k speed test requests daily(world wide). Can i rely on server list you described in README? Maybe you can sugges servers(way of choosing test-servers) that fit my case?

**Comment by bertrandmartel** [comment]
From https://github.com/bertrandmartel/speed-test-lib/blob/master/server_list.md, you have a few examples . You could choose the right server depending on the country you could find in speedtest.net server list for instance in http://www.speedtest.net/speedtest-servers.php. You also want to choose a server with low latency (ping response)
