### ISSUE TITLE
It's possible to get the float Mb\s?

### ISSUE THREAD

**Issue by ThallyssonKlein** [bertrandmartel/speed-test-lib#25]
Hi there. I'm testing this library, and I think it amazing. But I would like to get the float Mb\s of the speed test. Somebody know to tell me if it's possible?

**Comment by bertrandmartel** [comment]
You can get `SpeedTestReport` from different callback 
* `onDownloadFinished`
* `onDownloadProgress`
* `onUploadFinished`
* `onUploadProgress`

SpeedTestReport object has all information about the test at the moment the callback was triggered. Bitrate is given in `BigDecimal` type for better precision, you can convert it easily to any other type including float : 

```
float bps = report.getTransferRateBit().floatValue();
double bps = report.getTransferRateBit().doubleValue();
int bps = report.getTransferRateBit().intValue();
```

**Comment by ThallyssonKlein** [comment]
It works perfectly. Thank you for help me.
