### ISSUE TITLE
Simultaneous download/upload

### ISSUE THREAD

**Issue by DimaDDM** [bertrandmartel/speed-test-lib#26]
Hello. Can you also add instead of forceStopTask() methods for stop downloading or uploading task? Thanks.

**Comment by bertrandmartel** [comment]
Hello, `forceStopTask` does stop download or upload running task. Do you mean you want to launch simultaneously a download and upload and to be able to stop only download or upload ? In that case ,the library doesn't support simultaneous download/upload only queued download/upload task

**Comment by DimaDDM** [comment]
Simultaneous upload and download feature will be awesome.

**Comment by bertrandmartel** [comment]
I will see how to implement that, I would need also to add additional tests to ensure thread safety
