### ISSUE TITLE
Is there a good way to get the best server URL?

### ISSUE THREAD

**Issue by MikeZhou** [bertrandmartel/speed-test-lib#36]

**Comment by bertrandmartel** [comment]
From [server_list.md](https://github.com/bertrandmartel/speed-test-lib/blob/master/server_list.md), you have a few examples . You could choose the right server depending on the country you could find in speedtest.net server list for instance in http://www.speedtest.net/speedtest-servers.php. You also want to choose a server with low latency (ping response)
