### ISSUE TITLE
start***Download & start***Upload overrides with FTP account params

### ISSUE THREAD

**Issue by egrgdam** [bertrandmartel/speed-test-lib#40]
So as title says, could you please override mentioned methods so that we can use lib on custom FTP servers with appropriate FTP account credentials, not with Constant class you build in lib. So like:

startFixedDownload(java.lang.String uri, int maxDuration, int reportInterval, String ftpUsername, String ftpPassword) where uri is with ftp:// protocol prefix.

Best,
G

**Comment by bertrandmartel** [comment]
`userInfo` data is parsed in the URI, it can be used as 

```
speedTestSocket.startFixedDownload("ftp://username:password@your.server.net/100MB.zip");
```

This must be a valid URI scheme as : 

```
http:[//[user[:password]@]host[:port]][/path]
```

An example of ftp server with credentials tested is 

```
ftp://speedtest:speedtest@ftp.otenet.gr/test1Mb.db
```

**Comment by bertrandmartel** [comment]
Note that the default is anonymous authentication (user : anonymous, no password)
