### ISSUE TITLE
onError -- reports back URL

### ISSUE THREAD

**Issue by jveejay** [bertrandmartel/speed-test-lib#42]
Hi,

Great tool. Thank you for providing it. 

I am using it in Android, but I am having trouble. 

I get an error message. In the onError callback shown below I get the message as the URL. It simply spits out the primary URL path. Callback is shown below, and so is the logged error message.

                    @Override
                    public void onError(SpeedTestError speedTestError, String errorMessage) {
                        Log.d("onError", "[ERROR] " + errorMessage);
                    }

E.g. error message:
05-12 20:01:06.749 2583-3688/com.google.uxbandit D/onError: [ERROR] ipv4.bouygues.testdebit.info

What does it mean to get such an error message? When I access the URL i actually provide "http://ipv4.bouygues.testdebit.info/1M.iso" to start download it all works well elsewhere, as in I am able to download the file through my computer, as well as the Android emulator. 

Thanks,
vj.

**Comment by bertrandmartel** [comment]
Hello, can you print the `speedTestError` to see what type of error shows ?

**Comment by jveejay** [comment]
Hi,

I am running the app on the emulator and it looks like android emulator is having trouble resolving the hostname, as you can see in the attached image:

**Comment by jveejay** [comment]
Ah fixed it — needed to add the second line for instance in addition to the internet only .. odd.

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

**Comment by bertrandmartel** [comment]
Maybe it's the same as #4 , specify the DNS server with `-dns-server 8.8.8.8,8.8.4.4`. But there is no need for `ACCESS_NETWORK_STATE`. Note that I had this issue with Android Studio < 2.3 and specifying network speed as other than `Full`, if you don't mind try change network speed to `full` in your emulator configuration.
