### ISSUE TITLE
Not working on android?

### ISSUE THREAD

**Issue by zhihan** [bertrandmartel/speed-test-lib#43]
I used it on my android and got the following error: 

E/speedtest( 2132): Error occurred while parsing http frame
E/speedtest( 2132): Error content length is inconsistent
E/speedtest( 2132): Error status code -1

And the onError method of the listener is called.

I am using a Nexus 5 running android 5.1. I changed to a different server and the error is reproducible.

**Comment by zhihan** [comment]
It is reproducible on laptop as well. FWIW I am using a public Wifi. 

:examples:processResources
:examples:classes
:examples:downloadFile
20:52:17.288 [pool-2-thread-1] ERROR fr.bmartel.speedtest.examples.DownloadFileExample - error INVALID_HTTP_RESPONSE : Error occurred while parsing http frame
20:52:17.289 [pool-2-thread-1] ERROR fr.bmartel.speedtest.examples.DownloadFileExample - error INVALID_HTTP_RESPONSE : Error content length is inconsistent
20:52:17.289 [pool-2-thread-1] ERROR fr.bmartel.speedtest.examples.DownloadFileExample - error INVALID_HTTP_RESPONSE : Error status code -1

**Comment by bertrandmartel** [comment]
Maybe an issue with 2.testdebit.info, what is the result of : 
```
curl -v -X HEAD  http://2.testdebit.info/fichiers/1Mo.dat
```
For me : 

```
*   Trying 194.158.102.114...
* Connected to 2.testdebit.info (194.158.102.114) port 80 (#0)
> HEAD /fichiers/1Mo.dat HTTP/1.1
> Host: 2.testdebit.info
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Sat, 03 Jun 2017 01:36:14 GMT
< Server: Apache
< Last-Modified: Wed, 17 May 2017 05:48:03 GMT
< ETag: "f4240-54fb1d4e594c6"
< Accept-Ranges: bytes
< Content-Length: 1000000

```

**Comment by bertrandmartel** [comment]
I'll check the status code before checking the content-length it could lead to error if the response is a redirection (301/302)

**Comment by bertrandmartel** [comment]
It should work with version `1.30.1`, I will add more functional test for status code 200, 301, 302 w & w/o  body for download & upload
