### ISSUE TITLE
Irrelevant Results for downloading

### ISSUE THREAD

**Issue by burakatestepe** [bertrandmartel/speed-test-lib#44]
I created speed test for http downloading and uploading.

 Upload works and give me relevant results such as that if first time may 30mbits then such as 20 28 35 38 mbits. 

But when i use download, it gives me irrelevant results. For example, one time gives 2mbits and then i start again and gives 30mbits.  I cant give relevant values always. Its big problem for me. I download 4 times for giving values but its not enough. Can you advice something for this?

``
public class SpeedTestTask extends AsyncTask<Void, Void, String> {
		
       SpeedTestSocket speedTestSocket = new SpeedTestSocket();

	    @Override
	    protected String doInBackground(Void... params) {
	        speedTestSocket.addSpeedTestListener(new ISpeedTestListener() {

	            @Override
	            public void onCompletion(SpeedTestReport report) {
					if (startType == 6) 
					{
		            	System.out.println("[UL COMPLETED] rate in octet/s : " + report.getTransferRateOctet());
						BigDecimal a = new BigDecimal("1048576");
						System.out.println("[UL COMPLETED] rate in Mbit/s   : " + report.getTransferRateBit().divide(a));
						olduploadspeed = report.getTransferRateBit().divide(a);
						uploadspeed = olduploadspeed.setScale(2,RoundingMode.FLOOR);
						enablebutton = true;
						finishedupload = true;
					}
					else if(startType >= 1)
					{
						System.out.println("[DL COMPLETED] rate in octet/s : " + report.getTransferRateOctet());
						BigDecimal a = new BigDecimal("1048576");
						System.out.println("[DL COMPLETED] rate in Mbit/s : " + report.getTransferRateBit().divide(a));
						olddownloadspeed = report.getTransferRateBit().divide(a);
					    downloadspeed = olddownloadspeed.setScale(2,RoundingMode.FLOOR);
						startType++;
						if(startType == 6)
						{
						 finisheddownload = true;
					     speedTestSocket.startFixedUpload("http://2.testdebit.info/", 5000000,30000,500);
						}
						else if(startType > 1)
						{
						 speedTestSocket.startFixedDownload("http://2.testdebit.info/fichiers/20Mo.dat",15000,500);
						}	
					}
	            }

	            @Override
	            public void onError(SpeedTestError speedTestError, String errorMessage) {
	              }

	            @Override
	            public void onProgress(float percent, SpeedTestReport report) {
	    	        if (startType == 6)
	    	        {
						if (forcetoStop == true) {
							startType = 1;
							speedTestSocket.forceStopTask();
							speedTestSocket.clearListeners();
							speedTestSocket.closeSocket();
							uploadspeed = BigDecimal.ZERO;
							downloadspeed = BigDecimal.ZERO;
						} else {
							System.out.println("[UL PROGRESS] progress : "
									+ percent + "%");
							System.out.println("[UL PROGRESS] rate in octet/s : "
									+ report.getTransferRateOctet());
							BigDecimal a = new BigDecimal("1048576");
							System.out.println("[UL PROGRESS] rate in Mbit/s   : "
									+ report.getTransferRateBit().divide(a));
								olduploadspeed = report.getTransferRateBit().divide(a);
								uploadspeed = olduploadspeed.setScale(2,RoundingMode.FLOOR);
						}
	    	        }
	    	        else if (startType >= 1) 
	    	        {
						enablebutton = false;
						if (forcetoStop == true) {
							startType = 1;
							speedTestSocket.forceStopTask();
							speedTestSocket.clearListeners();
							speedTestSocket.closeSocket();
							downloadspeed = BigDecimal.ZERO;
							uploadspeed = BigDecimal.ZERO;
						} else {						
							System.out.println("[DL PROGRESS] progress : "
									+ percent + "%");
							System.out.println("[DL PROGRESS] rate in octet/s : "
									+ report.getTransferRateOctet());
							BigDecimal a = new BigDecimal("1048576");
							System.out.println("[DL PROGRESS] rate in Mbit/s : "
									+ report.getTransferRateBit().divide(a));
							olddownloadspeed = report.getTransferRateBit().divide(a);
							downloadspeed = olddownloadspeed.setScale(2,RoundingMode.FLOOR);
						}
	    			}
	            }

	            @Override
	            public void onInterruption() {
					if (startType == 6) {
						finisheddownload = true;
					}	
					if (forcetoStop == true) {
						speedTestSocket.forceStopTask();
						speedTestSocket.clearListeners();
						speedTestSocket.closeSocket();
						uploadspeed = BigDecimal.ZERO;
						downloadspeed = BigDecimal.ZERO;
						startType = 1;
						finisheddownload = false;
						finishedupload = false;
					} else {
						if(startType != 1) startAgain();
						else finishedupload = true;
					}
	            }
	        });
	        
	        if (startType == 6)
	        {
		        speedTestSocket.startFixedUpload("http://2.testdebit.info/", 50000000,30000,500);
	        }
	        else if (startType >= 1) 
	        {
				speedTestSocket.startFixedDownload("http://2.testdebit.info/fichiers/20Mo.dat",15000,500);
				startType++;
			}
	        return null;
	    }
	}

**Comment by bertrandmartel** [comment]
Try defining a setup time for download/upload in order to compute the transfer rate only after an amount of time : 

```java
speedTestSocket.setDownloadSetupTime(2000);
```

and 
```java
speedTestSocket.setUploadSetupTime(2000);
```
