### ISSUE TITLE
Is there a way to filter the connection through a proxy?

### ISSUE THREAD

**Issue by Jeffrey-Hackford** [bertrandmartel/speed-test-lib#47]
The library works great to connect to my server but what about through a proxy first?

Thanks!

**Comment by Jeffrey-Hackford** [comment]
Could you possibly post a snippet of code where this enhancement could go? Just to point me in the right direction. 

Thanks in advance! This library has already been a huge help to me.

**Comment by bertrandmartel** [comment]
You can now [use a proxy server](https://github.com/bertrandmartel/speed-test-lib#use-proxy-server) with the new release 1.31.1.
* it can be used with http download and upload
* the default port is 8080
* see [this example](https://github.com/bertrandmartel/speed-test-lib/blob/master/examples/src/main/java/fr/bmartel/speedtest/examples/DownloadFileProxyExample.java#L71)

Let me know if you encounter any problems
