### ISSUE TITLE
server web page

### ISSUE THREAD

**Issue by juniper275** [bertrandmartel/speed-test-lib#49]
Hi,

is there some example to do a receiver server?

BR

**Comment by bertrandmartel** [comment]
Hi,

You can set up a public Http or Ftp server. For Http you need to setup a POST endpoint for upload and a GET endpoint for download. There are plenty of examples on the web in a lot of different programming language

**Comment by juniper275** [comment]
thank you fpr the information, what does you mean fot GET and POST endpoint?

**Comment by juniper275** [comment]
Using tour API i see on debug (with obfuscated server name)

HEAD

 

POST http://********** HTTP/1.1

Host: ********

Accept: */*

Content-Length: 10000000

 

Socket

 

Socket[address=********""""/212.****,port=80,localPort=53850]

connectLock = {Object@5363}

impl = {PlainSocketImpl@5364} "Socket[address=***"*""/212.*****",port=80,localPort=53850]"

isBound = true

isClosed = true.  Wrong

isConnected = false. Wrong

isCreated = true

isInputShutdown = false

isOutputShutdown = false

localAddress = {Inet6Address@5365} "/::"

proxy = null

shadow$_klass_ = {Class@440} "class java.net.Socket"

shadow$_monitor_ = 1262471857


IsClosed = true isn't correct bit i don't know why
