### ISSUE TITLE
How do I start startFixedUpload after the startFixedDownload method is finished?

### ISSUE THREAD

**Issue by juniormj** [bertrandmartel/speed-test-lib#50]
How do I start startFixedUpload after the startFixedDownload method is finished?
The way I'm doing the return is: 
08-24 12:59:39.026 3908-4208/com.br.dominio.speedtestmdbrasil E/ERRORRRR: mSocket error
08-24 12:59:39.026 3908-4208/com.br.dominio.speedtestmdbrasil E/ERRORRRR: SOCKET_ERROR

class SpeedTestTask extends AsyncTask<String, String, String> {

        @Override
        protected String doInBackground(String... params) {

            final SpeedTestSocket speedTestSocket = new SpeedTestSocket();

            speedTestSocket.addSpeedTestListener(new ISpeedTestListener() {

                @Override
                public void onCompletion(SpeedTestReport report) {

                    downloadRate = report.getTransferRateBit().divide(MEGA_VALUE_PER_SECONDS).doubleValue();
                    downloadTime = ((double) report.getReportTime() - (double) report.getStartTime()) / 1000;
                    totalTime = uploadTime + downloadTime;
                    publishProgress(String.format("%.2f Mbits/s", downloadRate), downloadTime + " seg",
                            String.format("%.2f seg", totalTime), "100");
                    
                    //Upload
                    speedTestSocket.startFixedUpload("http://www.mdbrasil.com.br/",29099000,15000,500);
                    isFinished = true;
                    uploadRate = report.getTransferRateBit().divide(MEGA_VALUE_PER_SECONDS).doubleValue();
                    uploadTime = ((double) report.getReportTime() - (double) report.getStartTime()) / 1000;
                    totalTime = uploadTime + downloadTime;
                    publishProgress(String.format("%.2f Mbits/s", uploadRate), uploadTime + " seg",
                            String.format("%.2f seg", totalTime), 100 + "");

                }

                @Override
                public void onProgress(float percent, SpeedTestReport report) {
                    if(report.getSpeedTestMode().toString() == "DOWNLOAD") {
                        isDownload = true;
                        isUpload = false;
                        downloadRate = report.getTransferRateBit().divide(MEGA_VALUE_PER_SECONDS).doubleValue();
                        downloadTime = ((double) report.getReportTime() - (double) report.getStartTime()) / 1000;
                        totalTime = uploadTime + downloadTime;
                        publishProgress(String.format("%.2f Mbits/s", downloadRate), downloadTime + " seg",
                                String.format("%.2f seg", totalTime), (int) percent + "");
                        Log.i("Porcentagem", ""+percent);
                    } else if (report.getSpeedTestMode().toString() == "UPLOAD") {

                        isDownload = false;
                        isUpload = true;
                        uploadRate = report.getTransferRateBit().divide(MEGA_VALUE_PER_SECONDS).doubleValue();
                        Log.i("UPLOAD", report.getTransferRateBit().toString());
                        uploadTime = ((double) report.getReportTime() - (double) report.getStartTime()) / 1000;
                        totalTime = uploadTime + downloadTime;
                        publishProgress(String.format("%.2f Mbits/s", uploadRate), uploadTime + " seg",
                                String.format("%.2f seg", totalTime), (int) percent + "");
                    }
                }

                @Override
                public void onError(SpeedTestError speedTestError, String errorMessage) {
                    Log.e("ERRORRRR", errorMessage);
                    Log.e("ERRORRRR", speedTestError.toString());
                }
            });

            speedTestSocket.startFixedDownload("http://mdbrasil.com.br/500m.dat", 15000,500);
            return null;
        }

        protected void onProgressUpdate(String... values) {
            super.onProgressUpdate(values);

            if (isDownload) {
                labelDownloadRate.setText(values[0]);
                labelDownloadTime.setText(values[1]);
                labelTotalTime.setText(values[2]);
                progressBarSpeedTest.setProgress(Integer.parseInt(values[3]));
            } else if (isUpload) {
                labelUploadRate.setText(values[0]);
                labelUploadTime.setText(values[1]);
                labelTotalTime.setText(values[2]);
                progressBarSpeedTest.setProgress(Integer.parseInt(values[3]));
            }

            if (isFinished) {
                buttonStart.setText("Reiniciar teste");
                buttonStart.setEnabled(true);
            }
        }
    }

**Comment by juniormj** [comment]
Would you help me?

**Comment by bertrandmartel** [comment]
Thank you for reporting this, the socket was closed after the `onCompletion` call when `forceStopTask` was called, now this is fixed in `1.31.2`. 

As a side note,  everything running in `onProgress` is running in the same thread as the reading/writing thread so it may affect the timings, if `publishProgress` is time consuming run it in another thread
