### ISSUE TITLE
allocation exceeds

### ISSUE THREAD

**Issue by juniormj** [bertrandmartel/speed-test-lib#51]
@bertrandmartel,
Good Morning..
One more bug to debug

![screenshot_20170828_111958](https://user-images.githubusercontent.com/6633502/29777614-039e3cc4-8be3-11e7-9387-4a27a62f8cf9.png)

**Comment by bertrandmartel** [comment]
same as #34, use `speedTestSocket.setUploadStorageType(UploadStorageType.FILE_STORAGE);` to use file storage rather than `UploadStorageType.RAM_STORAGE` which is the default
