### ISSUE TITLE
Can you please tell me the upper bound limit and how can I setup and use my servers

### ISSUE THREAD

**Issue by avaiyahardik** [bertrandmartel/speed-test-lib#52]
This is great!

I want to know few things:
1. Can I test speed of 1 GBps using this library?
2. How can I setup my own servers to use in this library for ping, upload and download speed tests?
3. Is this library performing cleanup after performing the test?

**Comment by bertrandmartel** [comment]
You may want to check [this section](https://github.com/bertrandmartel/speed-test-lib#speed-test-issues) for further info about the scope of the library

Speed test server need to have a `POST` rest endpoint for upload and a `GET` rest endpoint for download, you can find a small list of speed test server [here](https://github.com/bertrandmartel/speed-test-lib/blob/master/server_list.md)

You can ping the server using the `ping` command for latency check

For uploading large file, use `speedTestSocket.setUploadStorageType(UploadStorageType.FILE_STORAGE);` which will store random data in a temporary file using [`File.createTempFile`](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#createTempFile(java.lang.String,%20java.lang.String)) which is deleted at the end of the operation
