### ISSUE TITLE
onError getting called

### ISSUE THREAD

**Issue by manujjagga421** [bertrandmartel/speed-test-lib#54]
this lib was working perfectly for me until today, whenever i try something onError is getting called and this is the message i am getting 
failed to connect to 2.testdebit.info/89.84.1.222 (port 80): connect failed: ECONNREFUSED (Connection refused)

**Comment by bertrandmartel** [comment]
Thanks, I've updated the url from 2.testdebit.info to ipv4.ikoula.testdebit.info
