### ISSUE TITLE
bitrate is very very

### ISSUE THREAD

**Issue by Hallaz** [bertrandmartel/speed-test-lib#56]
I compared 2 result one from this libs, and another from speedtest ookla with the same address..
(i have access to ookla regional test server and got address they use to test and fortunately I can use those address )

    START UPLOAD   http://xxx.xxx.xx.xx/speedtest/upload.php random filesize 1000000 * 5    
    .....................................................
    [UPLOAD_COMPLETED] rate in kbyte/s : 525.0446287999999
    [UPLOAD_COMPLETED] rate in kbit/s   : 4200.3570303999995
    [UPLOAD_COMPLETED] startTime  : 1523459673837
    [UPLOAD_COMPLETED] endTime   : 1523459683360
    [UPLOAD_COMPLETED] time   : 9523

    START DOWNLOAD  http://xxx.xxx.xx.xx/speedtest/random1500x1500.jpg 
    ........................
    [DOWNLOAD_COMPLETED] rate in kbyte/s : 1331.8154993
    [DOWNLOAD_COMPLETED] rate in kbit/s   : 10654.5239944
    [DOWNLOAD_COMPLETED] startTime  : 1523459683381
    [DOWNLOAD_COMPLETED] endTime   : 1523459686736
    [DOWNLOAD_COMPLETED] time   : 3355

and the result from speedtest ookla 
![screenshot_20180411-222301_speedtest](https://user-images.githubusercontent.com/4651302/38626522-fb6d45d0-3dd6-11e8-9e94-e50d83466428.jpg)

**Comment by Hallaz** [comment]
hello finally im looking deep into the codes and did some twek,
at
private void startSocketDownloadTask(final String protocol, final String hostname) {
....
                mTimeStart = System.currentTimeMillis(); // add here
                downloadReadingLoop();
                mTimeEnd = System.currentTimeMillis();
...
}

and got expected result < 1000kbps diff compared to ookla speedtest result..

**Comment by bertrandmartel** [comment]
@Hallaz Thanks a lot I will look into this

**Comment by bertrandmartel** [comment]
Thanks for raising this issue, the connection time was included in the speed test calculation for download mode :+1: The new release is 1.32.0. Let me know if you have any problem
